import Link from "next/link";
import { ExternalLink, Pencil, Plus, Search } from "lucide-react";
import { PageHeader } from "@/components/admin/page-header";
import { Card } from "@/components/ui/card";
import { buttonClass } from "@/components/ui/button";
import { getWeddingSummaries } from "@/features/weddings/repository";
import { formatWeddingDate } from "@/lib/utils";

export default async function WeddingsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  const params = await searchParams; const result = await getWeddingSummaries(params.q, params.status, Number(params.page) || 1);
  return <><PageHeader eyebrow="Wedding management" title="Every celebration" description={`${result.count} wedding${result.count === 1 ? "" : "s"} across the platform.`} actions={<Link className={buttonClass()} href="/admin/weddings/new"><Plus size={17}/>New wedding</Link>}/><Card className="filter-bar"><form><div className="search-field"><Search/><input aria-label="Search couples" name="q" placeholder="Search by couple" defaultValue={params.q}/></div><select aria-label="Filter by status" name="status" defaultValue={params.status ?? "all"}><option value="all">All statuses</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select><button className={buttonClass({ variant: "outline", size: "sm" })}>Filter</button></form></Card><Card className="table-card"><div className="wedding-table"><div className="table-head"><span>Couple</span><span>Date</span><span>Package</span><span>Theme</span><span>Status</span><span>Domain</span><span>Actions</span></div>{result.items.map((wedding)=><div className="table-row" key={wedding.id}><span><strong>{wedding.displayNames}</strong><small>/{wedding.slug}</small></span><span>{formatWeddingDate(wedding.weddingAt)}</span><span className="capitalize">{wedding.package}</span><span className="capitalize">{wedding.themeId.replaceAll("-"," ")}</span><span><i className={`status-badge ${wedding.status}`}>{wedding.status}</i></span><span>{wedding.customDomain ?? "—"}</span><span className="table-actions"><Link aria-label={`Preview ${wedding.displayNames}`} href={`/admin/weddings/${wedding.id}/preview`}><ExternalLink/></Link><Link aria-label={`Edit ${wedding.displayNames}`} href={`/admin/weddings/${wedding.id}/edit/basics`}><Pencil/></Link></span></div>)}</div>{!result.items.length && <div className="empty-state"><h3>No weddings found</h3><p>Adjust the filters or create a new wedding.</p></div>}</Card></>;
}
