"use client";

import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarPlus, ChevronDown, Clock3, MapPin, Menu as MenuIcon, Music2, Pause, Share2, Volume1, VolumeX, X } from "lucide-react";
import type { WeddingSite } from "@/features/weddings/types";
import { formatWeddingDate, formatWeddingTime } from "@/lib/utils";
import { sectionEntitlement } from "@/features/entitlements";

const fontMap: Record<string,string> = { "Cormorant Garamond":"var(--font-cormorant)", "Playfair Display":"var(--font-playfair)", "DM Serif Display":"var(--font-dm-serif)", Manrope:"var(--font-manrope)", Inter:"var(--font-inter)", Lora:"var(--font-lora)" };
const titleMap: Record<string,string> = { welcome:"Welcome",story:"Our story",timeline:"Our journey",ceremony:"Ceremony",reception:"Reception",schedule:"The day",wedding_party:"Our people",dress_code:"Dress code",menu:"Menu",gallery:"Gallery",accommodation:"Where to stay",transportation:"Getting there",registry:"With love",faq:"Questions",rsvp:"Kindly respond",contact:"Contact",closing:"Until then" };
const mediaUrl=(id?:string)=>id?`/api/media/${id}`:"";

function useCountdown(target:string){const [now,setNow]=useState(0);useEffect(()=>{const tick=()=>setNow(Date.now());const immediate=setTimeout(tick,0);const timer=setInterval(tick,1000);return()=>{clearTimeout(immediate);clearInterval(timer)}},[]);const remaining=now===0?0:Math.max(0,new Date(target).getTime()-now);return {days:Math.floor(remaining/86400000),hours:Math.floor(remaining/3600000)%24,minutes:Math.floor(remaining/60000)%60,seconds:Math.floor(remaining/1000)%60};}

export function WeddingSiteRenderer({ wedding, preview=false }:{wedding:WeddingSite;preview?:boolean}){
  const [opened,setOpened]=useState(preview);const [menuOpen,setMenuOpen]=useState(false);const [playing,setPlaying]=useState(false);const [muted,setMuted]=useState(false);const [volume,setVolume]=useState(.55);const audioRef=useRef<HTMLAudioElement>(null);const countdown=useCountdown(wedding.weddingAt);
  const sections=useMemo(()=>wedding.sections.filter(s=>s.enabled&&sectionEntitlement(s.key,wedding.entitlements)).sort((a,b)=>a.position-b.position),[wedding]);
  const css={"--w-primary":wedding.theme.primary,"--w-secondary":wedding.theme.secondary,"--w-accent":wedding.theme.accent,"--w-heading":fontMap[wedding.theme.headingFont]??fontMap["Cormorant Garamond"],"--w-body":fontMap[wedding.theme.bodyFont]??fontMap.Manrope} as React.CSSProperties;
  async function openInvitation(){setOpened(true);if(wedding.media.music&&wedding.entitlements.backgroundMusic&&audioRef.current){try{await audioRef.current.play();setPlaying(true)}catch{setPlaying(false)}}}
  function toggleMusic(){if(!audioRef.current)return;if(audioRef.current.paused){audioRef.current.play();setPlaying(true)}else{audioRef.current.pause();setPlaying(false)}}
  const shareText=encodeURIComponent(`You’re invited to celebrate ${wedding.displayNames} on ${formatWeddingDate(wedding.weddingAt,wedding.timezone)}. ${typeof window!=="undefined"?window.location.href:""}`);
  const hero=mediaUrl(wedding.media.hero);
  const heroFocal=wedding.mediaFocalPoints.hero??{x:50,y:22};
  const heroPosition={objectPosition:`${heroFocal.x}% ${heroFocal.y}%`};
  return <div className={`wedding-site theme-${wedding.theme.id} radius-${wedding.theme.radius} motion-${wedding.theme.motion}`} style={css} data-opened={opened}>
    {wedding.media.music&&<audio ref={audioRef} src={mediaUrl(wedding.media.music)} loop muted={muted} onVolumeChange={()=>audioRef.current&&setVolume(audioRef.current.volume)}/>} 
    {!opened&&<div className="invitation-gate">{hero&&<Image src={hero} alt="" fill priority sizes="100vw" style={heroPosition} unoptimized/>}<div className="gate-overlay"/><div className="gate-content"><p>Together with their families</p><h1>{wedding.displayNames}</h1><span>{formatWeddingDate(wedding.weddingAt,wedding.timezone)}</span><button onClick={openInvitation}>Open invitation <ChevronDown/></button></div></div>}
    <header className="wedding-nav"><a className="couple-mark" href="#hero">{wedding.partnerOneName.charAt(0)} <i>&</i> {wedding.partnerTwoName.charAt(0)}</a><nav>{sections.filter(s=>!["opening","hero","countdown","closing"].includes(s.key)).slice(0,6).map(s=><a key={s.key} href={`#${s.key}`}>{titleMap[s.key]??s.key}</a>)}</nav><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><MenuIcon/></button></header>
    {menuOpen&&<div className="mobile-drawer"><button aria-label="Close navigation" onClick={()=>setMenuOpen(false)}><X/></button>{sections.filter(s=>!["opening","hero"].includes(s.key)).map(s=><a key={s.key} href={`#${s.key}`} onClick={()=>setMenuOpen(false)}>{titleMap[s.key]??s.key}</a>)}</div>}
    <main>{sections.map(section=><WeddingSection key={section.key} section={section.key} wedding={wedding} hero={hero} heroPosition={heroPosition} countdown={countdown} shareText={shareText}/>)}</main>
    {wedding.media.music&&wedding.entitlements.backgroundMusic&&opened&&<div className="audio-controls"><button aria-label={playing?"Pause music":"Play music"} onClick={toggleMusic}>{playing?<Pause/>:<Music2/>}</button><button aria-label={muted?"Unmute music":"Mute music"} onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX/>:<Volume1/>}</button><label><span className="sr-only">Music volume</span><input type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>{const value=Number(e.target.value);setVolume(value);if(audioRef.current)audioRef.current.volume=value}}/></label></div>}
  </div>;
}

function WeddingSection({section,wedding,hero,heroPosition,countdown,shareText}:{section:string;wedding:WeddingSite;hero:string;heroPosition:{objectPosition:string};countdown:{days:number;hours:number;minutes:number;seconds:number};shareText:string}){
  const content=wedding.content; const event=wedding.events.find(e=>e.type===section);
  if(section==="opening")return null;
  if(section==="hero")return <section id="hero" className="wed-hero">{hero?<Image src={hero} alt={`${wedding.displayNames} wedding portrait`} fill priority sizes="100vw" style={heroPosition} unoptimized/>:<div className="hero-placeholder"/>}<div className="wed-hero-overlay"/><div><p>We’re getting married</p><h1>{wedding.partnerOneName}<i>&</i>{wedding.partnerTwoName}</h1><span>{formatWeddingDate(wedding.weddingAt,wedding.timezone)}</span><small>Jamaica</small></div></section>;
  if(section==="countdown")return <section id="countdown" className="countdown-section"><p>Until we say “I do”</p><div>{Object.entries(countdown).map(([label,value])=><span key={label}><strong>{String(value).padStart(2,"0")}</strong><small>{label}</small></span>)}</div></section>;
  if(section==="welcome"&&content.introduction)return <StorySection id={section} eyebrow="With joyful hearts" title="You are invited"><p className="lead">{content.introduction}</p><p className="hashtag">{content.hashtag}</p></StorySection>;
  if(section==="story"&&(content.coupleStory||content.engagementStory))return <StorySection id={section} eyebrow="How it began" title="Our story"><p>{content.coupleStory}</p>{content.engagementStory&&<><h3>The proposal</h3><p>{content.engagementStory}</p></>}</StorySection>;
  if((section==="ceremony"||section==="reception")&&event)return <section id={section} className="event-section"><p className="wed-eyebrow">{section}</p><h2>{event.venue}</h2><div className="event-meta"><span><Clock3/>{formatWeddingTime(event.startsAt,wedding.timezone)}</span><span><MapPin/>{event.address}, {event.parish}</span></div>{event.mapsUrl&&<a className="wed-button" href={event.mapsUrl} target="_blank" rel="noreferrer">View directions</a>}{event.parkingNotes&&<p>{event.parkingNotes}</p>}</section>;
  if(section==="schedule"&&wedding.schedule.length)return <ListSection id={section} eyebrow="Order of celebration" title="The day">{wedding.schedule.map(item=><article className="schedule-row" key={item.id}><time>{formatWeddingTime(item.startsAt,wedding.timezone)}</time><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</ListSection>;
  if(section==="dress_code"&&content.dressCode)return <StorySection id={section} eyebrow="What to wear" title="Dress code"><p className="lead">{content.dressCode}</p></StorySection>;
  if(section==="menu"&&wedding.menu.length)return <ListSection id={section} eyebrow="Made with love" title="Menu"><div className="menu-list">{wedding.menu.map(item=><article key={item.id}><small>{item.category}</small><h3>{item.name}</h3><p>{item.description}</p></article>)}</div></ListSection>;
  if(section==="wedding_party"&&wedding.party.length)return <ListSection id={section} eyebrow="Beside us" title="Our people"><div className="party-grid">{wedding.party.map(person=><article key={person.id}>{person.mediaId&&<Image src={mediaUrl(person.mediaId)} alt={person.name} width={360} height={450} unoptimized/>}<h3>{person.name}</h3><small>{person.role}</small><p>{person.biography}</p></article>)}</div></ListSection>;
  if(section==="gallery"&&wedding.gallery.length)return <ListSection id={section} eyebrow="Favourite moments" title="Gallery"><div className="gallery-grid">{wedding.gallery.map((image,index)=><figure key={image.id}><Image src={mediaUrl(image.mediaId)} alt={image.altText} width={index%3===0?900:600} height={index%3===0?1100:700} sizes="(max-width: 720px) 100vw, 33vw" unoptimized/><figcaption>{image.caption}</figcaption></figure>)}</div></ListSection>;
  if(section==="accommodation"&&content.accommodation)return <StorySection id={section} eyebrow="Stay awhile" title="Accommodation"><p>{content.accommodation}</p></StorySection>;
  if(section==="transportation"&&wedding.events.some(e=>e.transportationNotes))return <StorySection id={section} eyebrow="Plan your journey" title="Transportation"><p>{wedding.events.find(e=>e.transportationNotes)?.transportationNotes}</p></StorySection>;
  if(section==="registry"&&content.registry)return <StorySection id={section} eyebrow="Your presence is a gift" title="Registry"><p>{content.registry}</p></StorySection>;
  if(section==="faq"&&wedding.faqs.length)return <ListSection id={section} eyebrow="Good to know" title="Questions"><div className="faq-list">{wedding.faqs.map(faq=><details key={faq.id}><summary>{faq.question}<ChevronDown/></summary><p>{faq.answer}</p></details>)}</div></ListSection>;
  if(section==="timeline"&&wedding.timeline.length)return <ListSection id={section} eyebrow="From then to forever" title="Our journey"><div className="timeline-list">{wedding.timeline.map(item=><article key={item.id}><time>{new Date(`${item.occurredOn}T12:00:00`).getFullYear()}</time><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></ListSection>;
  if(section==="rsvp"&&content.rsvpMode&&content.rsvpTarget){const href=content.rsvpMode==="email"?`mailto:${content.rsvpTarget}`:content.rsvpMode==="whatsapp"?`https://wa.me/${content.rsvpTarget.replace(/\D/g,"")}`:content.rsvpTarget;return <section id={section} className="rsvp-section"><p className="wed-eyebrow">We hope you’ll join us</p><h2>Kindly respond</h2><p>Please let us know whether you can celebrate with us.</p><a className="wed-button" href={href} target="_blank" rel="noreferrer">RSVP now</a></section>}
  if(section==="contact"&&content.contactInformation)return <StorySection id={section} eyebrow="Need a little help?" title="Contact"><p>{content.contactInformation}</p></StorySection>;
  if(section==="closing")return <section id={section} className="closing-section"><p>{content.closingMessage}</p><h2>{wedding.displayNames}</h2><div className="share-row"><a href={`https://wa.me/?text=${shareText}`} target="_blank" rel="noreferrer"><Share2/>Share on WhatsApp</a>{wedding.entitlements.addToCalendar&&<a href={`/${wedding.slug}/calendar.ics`}><CalendarPlus/>Add to calendar</a>}</div></section>;
  return null;
}
function StorySection({id,eyebrow,title,children}:{id:string;eyebrow:string;title:string;children:React.ReactNode}){return <section id={id} className="story-section"><p className="wed-eyebrow">{eyebrow}</p><h2>{title}</h2><div className="story-copy">{children}</div></section>}
function ListSection({id,eyebrow,title,children}:{id:string;eyebrow:string;title:string;children:React.ReactNode}){return <section id={id} className="list-section"><p className="wed-eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>}
