import Link from "next/link";
import { ExternalLink, Info } from "lucide-react";
import { PageHeader } from "@/components/admin/page-header";
import { WizardNav } from "@/components/admin/wizard-nav";
import { MediaUploader } from "@/components/admin/media-uploader";
import { MediaLibrary } from "@/components/admin/media-library";
import { SectionSorter } from "@/components/admin/section-sorter";
import { Card } from "@/components/ui/card";
import { Button, buttonClass } from "@/components/ui/button";
import { Field, SelectField, TextareaField } from "@/components/ui/field";
import { changeWeddingStatus, saveBasics, saveContent, saveDesign, saveEvents, saveSections } from "@/features/weddings/actions";
import { getAdminWedding } from "@/features/weddings/repository";
import { getEntitlements } from "@/features/entitlements";
import { JAMAICAN_PARISHES, SECTION_KEYS, WIZARD_STEPS } from "@/lib/config/brand";
import type { PackageName } from "@/features/weddings/types";

export const dynamic = "force-dynamic";
type Row = Record<string, unknown>;
const one = (value: unknown) => Array.isArray(value) ? (value[0] as Row | undefined) ?? {} : (value as Row | null) ?? {};
const list = (value: unknown) => Array.isArray(value) ? value as Row[] : [];
const val = (row: Row, key: string, fallback = "") => typeof row[key] === "string" ? row[key] as string : fallback;
const dateValue = (value: unknown) => typeof value === "string" ? value.slice(0,10) : "";
const timeValue = (value: unknown) => typeof value === "string" ? new Date(value).toISOString().slice(11,16) : "";

export default async function EditWeddingPage({ params, searchParams }: { params: Promise<{ id: string; step: string }>; searchParams: Promise<{ error?: string }> }) {
  const {id,step}=await params; const query=await searchParams;
  if(!WIZARD_STEPS.some(item=>item.slug===step)) return <p>Unknown step.</p>;
  const raw=await getAdminWedding(id) as unknown as Row; const content=one(raw.wedding_content); const theme=one(raw.wedding_theme_settings); const events=list(raw.wedding_events); const sections=list(raw.wedding_sections).sort((a,b)=>Number(a.position)-Number(b.position)); const media=list(raw.wedding_media).filter(item=>item.active!==false); const packageName=val(raw,"package","essential") as PackageName; const entitlements=getEntitlements(packageName);
  const schedule=list(raw.wedding_schedule_items).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)); const menu=list(raw.wedding_menu_items).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)); const faqs=list(raw.wedding_faqs).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)); const party=list(raw.wedding_party_members).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)); const timeline=list(raw.wedding_timeline_items).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));
  const ceremony=events.find(event=>event.event_type==="ceremony")??{}; const reception=events.find(event=>event.event_type==="reception")??{};
  return <><PageHeader eyebrow={`Editing · ${packageName}`} title={val(raw,"display_names")} description={`magicalweddings.com/${val(raw,"slug")}`} actions={<Link className={buttonClass({variant:"outline"})} href={`/admin/weddings/${id}/preview`}><ExternalLink size={16}/>Preview</Link>}/><WizardNav weddingId={id} current={step}/>{query.error&&<p className="alert error">{query.error}</p>}
    {step==="basics"&&<Card className="wizard-card"><form className="form-grid" action={saveBasics}><Hidden id={id}/><Field label="Partner one name" name="partnerOneName" defaultValue={val(raw,"partner_one_name")} required/><Field label="Partner two name" name="partnerTwoName" defaultValue={val(raw,"partner_two_name")} required/><Field className="span-2" label="Display names" name="displayNames" defaultValue={val(raw,"display_names")} required/><Field label="Wedding date" name="weddingDate" type="date" defaultValue={dateValue(raw.wedding_at)} required/><Field label="Wedding time" name="weddingTime" type="time" defaultValue={timeValue(raw.wedding_at)} required/><SelectField label="Timezone" name="timezone" defaultValue={val(raw,"timezone","America/Jamaica")}><option>America/Jamaica</option></SelectField><SelectField label="Package" name="package" defaultValue={packageName}><option value="essential">Essential</option><option value="signature">Signature</option><option value="bespoke">Bespoke</option></SelectField><Field className="span-2" label="URL slug" name="slug" defaultValue={val(raw,"slug")} required/><Field label="Contact email" name="contactEmail" type="email" defaultValue={val(raw,"contact_email")}/><Field label="Contact phone" name="contactPhone" defaultValue={val(raw,"contact_phone")}/><Next/></form></Card>}
    {step==="events"&&<Card className="wizard-card"><form className="form-grid" action={saveEvents}><Hidden id={id}/>
      <fieldset className="span-2 nested-fields"><legend>Ceremony</legend><Field label="Venue" name="ceremonyVenue" defaultValue={val(ceremony,"venue_name")} required/><Field label="Address" name="ceremonyAddress" defaultValue={val(ceremony,"address")} required/><Parish name="ceremonyParish" value={val(ceremony,"parish")}/><Field label="Date" name="ceremonyDate" type="date" defaultValue={dateValue(ceremony.starts_at)} required/><Field label="Start time" name="ceremonyTime" type="time" defaultValue={timeValue(ceremony.starts_at)} required/><Field className="span-2" label="Ceremony Google Maps link" name="ceremonyMapsUrl" type="url" defaultValue={val(ceremony,"maps_url")} placeholder="https://maps.google.com/…"/></fieldset>
      <fieldset className="span-2 nested-fields"><legend>Reception</legend><Field label="Venue" name="receptionVenue" defaultValue={val(reception,"venue_name")}/><Field label="Address" name="receptionAddress" defaultValue={val(reception,"address")}/><Parish name="receptionParish" value={val(reception,"parish")}/><Field label="Date" name="receptionDate" type="date" defaultValue={dateValue(reception.starts_at)}/><Field label="Start time" name="receptionTime" type="time" defaultValue={timeValue(reception.starts_at)}/><Field className="span-2" label="Reception Google Maps link" name="receptionMapsUrl" type="url" defaultValue={val(reception,"maps_url")} placeholder="https://maps.google.com/…"/></fieldset>
      <TextareaField label="Transportation notes" name="transportationNotes" defaultValue={val(reception,"transportation_notes")}/><TextareaField label="Parking notes" name="parkingNotes" defaultValue={val(reception,"parking_notes")}/><Next/></form></Card>}
    {step==="content"&&<Card className="wizard-card"><form className="form-grid" action={saveContent}><Hidden id={id}/><input type="hidden" name="weddingDate" value={dateValue(raw.wedding_at)}/><TextareaField className="span-2" label="Introductory message" name="introduction" defaultValue={val(content,"introduction")}/><TextareaField className="span-2" label="Couple’s story" name="coupleStory" defaultValue={val(content,"couple_story")}/><TextareaField className="span-2" label="Engagement story" name="engagementStory" defaultValue={val(content,"engagement_story")}/><Field label="Wedding hashtag" name="hashtag" defaultValue={val(content,"hashtag")}/><Field label="Dress code" name="dressCode" defaultValue={val(content,"dress_code")}/><TextareaField label="Accommodation information" name="accommodation" defaultValue={val(content,"accommodation")}/><TextareaField label="Registry information" name="registry" defaultValue={val(content,"registry_information")}/><TextareaField label="Contact information" name="contactInformation" defaultValue={val(content,"contact_information")}/><TextareaField label="Closing message" name="closingMessage" defaultValue={val(content,"closing_message")}/><SelectField label="Version 1 RSVP channel" name="rsvpMode" defaultValue={val(content,"rsvp_mode","external_url")}><option value="external_url">External form</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option></SelectField><Field label="RSVP link or address" name="rsvpTarget" defaultValue={val(content,"rsvp_target")}/><Structured label="Schedule" name="scheduleItems" hint="One per line: 16:00 | Ceremony | Garden" value={schedule.map(x=>`${timeValue(x.starts_at)} | ${val(x,"title")} | ${val(x,"description")}`).join("\n")}/><Structured label="Menu" name="menuItems" hint="One per line: Main | Jerk chicken | Coconut rice" value={menu.map(x=>`${val(x,"category")} | ${val(x,"name")} | ${val(x,"description")}`).join("\n")}/><Structured label="FAQs" name="faqItems" hint="One per line: Question | Answer" value={faqs.map(x=>`${val(x,"question")} | ${val(x,"answer")}`).join("\n")}/><Structured label="Wedding party" name="partyItems" hint="One per line: Name | Role | Biography" value={party.map(x=>`${val(x,"name")} | ${val(x,"role")} | ${val(x,"biography")}`).join("\n")}/><Structured label="Relationship timeline" name="timelineItems" hint="One per line: 2024-02-14 | The proposal | Description" value={timeline.map(x=>`${val(x,"occurred_on")} | ${val(x,"title")} | ${val(x,"description")}`).join("\n")}/><p className="form-note span-2"><Info/>Each line is saved as its own structured database record. Use the vertical bar to separate fields.</p><Next/></form></Card>}
    {step==="design"&&<Card className="wizard-card"><form className="form-grid" action={saveDesign}><Hidden id={id}/><SelectField label="Theme" name="themeId" defaultValue={val(theme,"theme_id","timeless-romance")}><option value="timeless-romance">Timeless Romance</option><option value="tropical-elegance">Tropical Elegance</option><option value="modern-minimal">Modern Minimal</option></SelectField><div className="entitlement-note">{entitlements.themeCustomization?"Full theme controls included":"Essential saves the selected curated preset; custom values are ignored server-side."}</div><Field label="Primary colour" name="primaryColor" type="color" defaultValue={val(theme,"primary_color","#5f2438")}/><Field label="Secondary colour" name="secondaryColor" type="color" defaultValue={val(theme,"secondary_color","#fffaf3")}/><Field label="Accent colour" name="accentColor" type="color" defaultValue={val(theme,"accent_color","#bd8c54")}/><SelectField label="Heading font" name="headingFont" defaultValue={val(theme,"heading_font","Cormorant Garamond")}><option>Cormorant Garamond</option><option>Playfair Display</option><option>DM Serif Display</option></SelectField><SelectField label="Body font" name="bodyFont" defaultValue={val(theme,"body_font","Manrope")}><option>Manrope</option><option>Inter</option><option>Lora</option></SelectField><SelectField label="Background" name="backgroundStyle" defaultValue={val(theme,"background_style","paper")}><option value="plain">Plain</option><option value="paper">Paper</option><option value="soft">Soft</option><option value="editorial">Editorial</option></SelectField><SelectField label="Buttons" name="buttonStyle" defaultValue={val(theme,"button_style","solid")}><option value="solid">Solid</option><option value="outline">Outline</option><option value="pill">Pill</option></SelectField><SelectField label="Border radius" name="radius" defaultValue={val(theme,"border_radius","soft")}><option value="none">None</option><option value="soft">Soft</option><option value="round">Round</option></SelectField><SelectField label="Animation intensity" name="motion" defaultValue={val(theme,"animation_intensity","subtle")}><option value="none">None</option><option value="subtle">Subtle</option><option value="expressive">Expressive</option></SelectField><SelectField label="Decorative elements" name="decoration" defaultValue={val(theme,"decorative_elements","fine-lines")}><option value="none">None</option><option value="fine-lines">Fine lines</option><option value="botanical">Botanical</option><option value="geometric">Geometric</option></SelectField><Next/></form></Card>}
    {step==="media"&&<Card className="wizard-card"><div className="media-grid"><MediaUploader weddingId={id} purpose="hero" title="Hero image" accept="image/jpeg,image/png,image/webp,image/avif"/><MediaUploader weddingId={id} purpose="portrait" title="Couple portrait" accept="image/jpeg,image/png,image/webp,image/avif"/><MediaUploader weddingId={id} purpose="gallery" title={`Gallery · ${entitlements.galleryLimit} image limit`} accept="image/jpeg,image/png,image/webp,image/avif"/><MediaUploader weddingId={id} purpose="texture" title="Background texture" accept="image/jpeg,image/png,image/webp,image/avif"/>{entitlements.backgroundMusic?<MediaUploader weddingId={id} purpose="music" title="Background music" accept="audio/mpeg,audio/mp4,audio/ogg"/>:<div className="upload-card locked-card"><strong>Background music</strong><p className="muted">Available with Signature and Bespoke.</p></div>}</div><MediaLibrary items={media.map(item=>({id:val(item,"id"),purpose:val(item,"purpose"),mimeType:val(item,"mime_type"),altText:val(item,"alt_text"),byteSize:Number(item.byte_size) || 0}))}/><div className="form-actions"><Link className={buttonClass()} href={`/admin/weddings/${id}/edit/sections`}>Continue to sections</Link></div></Card>}
    {step==="sections"&&<Card className="wizard-card"><form action={saveSections}><Hidden id={id}/><SectionSorter initial={SECTION_KEYS.map((key)=>{const saved=sections.find(item=>item.section_key===key);const locked=(key==="timeline"&&!entitlements.timeline)||(key==="wedding_party"&&!entitlements.weddingParty)||(key==="accommodation"&&!entitlements.accommodation)||(key==="transportation"&&!entitlements.transportation)||(key==="faq"&&!entitlements.faq);return {key,enabled:Boolean(saved?.enabled),locked};})}/></form></Card>}
    {step==="publish"&&<Card className="wizard-card publish-card"><div><p className="eyebrow">Current status</p><h2 className="capitalize">{val(raw,"status")}</h2>{Boolean(raw.has_unpublished_changes)&&<p className="alert warning">Unpublished changes are saved in the builder. The public site still shows the last published version.</p>}<p>Preview the working version at all three target sizes, then publish it now or choose a future time.</p><Link className={buttonClass({variant:"outline"})} href={`/admin/weddings/${id}/preview`}>Open responsive preview</Link></div><form action={changeWeddingStatus}><Hidden id={id}/><div className="publish-actions"><Button name="statusAction" value="publish">{Boolean(raw.has_unpublished_changes)?"Publish changes":"Publish now"}</Button><Button variant="outline" name="statusAction" value="draft">Unpublish to draft</Button><Button variant="danger" name="statusAction" value="archive">Archive</Button></div><div className="schedule-box"><Field label="Schedule publication" name="publishAt" type="datetime-local"/><Button variant="outline" name="statusAction" value="schedule">Schedule</Button></div></form></Card>}
  </>;
}
function Hidden({id}:{id:string}){return <input type="hidden" name="weddingId" value={id}/>}
function Next(){return <div className="form-actions span-2"><Button type="submit">Save & continue</Button></div>}
function Parish({name,value}:{name:string;value:string}){return <SelectField label="Parish" name={name} defaultValue={value}>{JAMAICAN_PARISHES.map(p=><option key={p}>{p}</option>)}</SelectField>}
function Structured({label,name,hint,value}:{label:string;name:string;hint:string;value:string}){return <TextareaField className="span-2" label={label} name={name} hint={hint} defaultValue={value}/>}
